const ASHEN_CAMPAIGN = [
{id:1,title:'The Last Ember',region:'Sanctuary & Ember Grove',theme:'Awakening',summary:'You wake beneath the last light with an ember that should not exist. Lyra asks you to decide whether the sanctuary deserves protection or the truth.',activities:['NPC dialogue','Ember gathering','First reputation choice','Sanctuary exploration'],choice:'Protect the sanctuary / ask for the truth',items:['Ashen Core','Emberleaf Charm','Sanctuary Sigil']},
{id:2,title:'The Bell Beneath Hollow',region:'Hollow Ruins',theme:'Memory',summary:'A bell rings beneath a ruined district and causes forgotten memories to surface. Orren believes someone is calling from below.',activities:['Echo investigation','Memory fragments','Ruins puzzle','NPC trust'],choice:'Silence the bell / learn who is calling',items:['Bellglass Fragment','Memory Thread','Hollow Lantern']},
{id:3,title:'Veil of Tides',region:'Veil Sea',theme:'Discovery',summary:'A road appears only during low tide. Crossing it reveals a drowned archive containing records that contradict the sanctuary history.',activities:['Tide timing','Archive search','Map fragments','Hidden rooms'],choice:'Seal the archive / publish the record',items:['Tideglass Compass','Drowned Archive Seal','Pearl of Recall']},
{id:4,title:'The Crownless City',region:'Crownlands',theme:'Politics',summary:'The old capital has no ruler, but every district claims to speak for the lost crown. Your reputation determines who will trust you.',activities:['Faction reputation','District errands','Public choice','City exploration'],choice:'Unite the districts / let them remain independent',items:['Crownless Signet','District Ledger','Royal Thread']},
{id:5,title:'Garden of Sleeping Stars',region:'Starfall Garden',theme:'Wonder',summary:'A garden blooms only at night. Each flower contains a memory belonging to someone who vanished from the kingdom.',activities:['Night exploration','Memory collection','Constellation puzzle','Companion quest'],choice:'Return the memories / preserve them',items:['Starpetal','Nightglass Vial','Astral Seed']},
{id:6,title:'The Nameless Choir',region:'Choir Catacombs',theme:'Identity',summary:'An underground choir repeats the names of forgotten travelers. One voice belongs to someone connected to your own past.',activities:['Audio clues','Name restoration','Lore investigation','Optional companion scene'],choice:'Restore every name / follow your own voice',items:['Choir Ribbon','Namekeeper Token','Resonance Pearl']},
{id:7,title:'Ashfall Winter',region:'Ember March',theme:'Survival',summary:'The sky turns grey and the sanctuary begins losing warmth. Communities must decide what to save before the ashfall reaches them.',activities:['Resource routes','Settlement support','Timed world event','Community reputation'],choice:'Save the sanctuary / divide resources equally',items:['Warmth Crystal','Ashweave Cloak','Hearth Memory']},
{id:8,title:'The Glass Observatory',region:'Glass Observatory',theme:'Truth',summary:'An ancient observatory can show possible futures, but every vision changes when another choice is made.',activities:['Constellation puzzle','Future visions','Branching dialogue','Secret room hunt'],choice:'Trust one future / reject all predictions',items:['Future Lens','Glass Astrolabe','Prism Note']},
{id:9,title:'The Starless Depths',region:'Starless Depths',theme:'Reckoning',summary:'The deepest road reflects every major choice you made. Old allies may return, but not necessarily with the same intentions.',activities:['Choice callbacks','Elite encounters','Rare collection','Reputation checks'],choice:'Accept the consequences / rewrite one memory',items:['Starless Relic','Echo Crownlet','Depth Map']},
{id:10,title:'The New Dawn',region:'The Last Ember',theme:'Legacy',summary:'The final chapter asks what kind of world your journey created. Your reputation, collection, choices and relationships determine the ending.',activities:['World-state finale','Allied NPC callbacks','Legacy challenge','Season record'],choice:'Preserve the old world / build a new one',items:['Dawn Sigil','Legacy Codex','Crown of Embers']}
];