const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),questTitle=$('questTitle'),questDesc=$('questDesc'),objective=$('objective'),questCount=$('questCount'),regionLabel=$('regionLabel'),dayLabel=$('dayLabel'),locationName=$('locationName'),locationHint=$('locationHint'),interaction=$('interaction'),dialogue=$('dialogue'),speakerName=$('speakerName'),speakerRole=$('speakerRole'),dialogueText=$('dialogueText'),choices=$('choices'),journal=$('journal'),journalBody=$('journalBody'),toast=$('toast'),pause=$('pause'),result=$('result');
let W=1200,H=700,dpr=1,last=0,paused=false,ended=false,keys={},mouse={x:600,y:350},particles=[],enemies=[],time=0,toastTimer=0;
const state={day:1,quest:0,coins:40,shards:0,echoes:0,rep:{lyra:0,orren:0,seer:0},flags:{gate:false,ruins:false,truth:false},log:["You woke beneath the sanctuary with an ember glowing in your palm."]};
const player={x:500,y:610,r:16,hp:100,stamina:100,inv:0,attack:0,attackCd:0,angle:-1.57,speed:190};
const npcs=[{id:'lyra',name:'Lyra',role:'Sanctuary Keeper',x:420,y:430,color:'#d18b5e'},{id:'orren',name:'Orren',role:'Wayfinder',x:790,y:430,color:'#8c9bb5'},{id:'seer',name:'The Seer',role:'Keeper of Echoes',x:1160,y:300,color:'#a184c8'}];
const places=[{id:'sanctuary',name:'Sanctuary',x:400,y:420,r:155,unlocked:true,hint:'A safe place beneath the last light.'},{id:'ashen_gate',name:'Ashen Gate',x:690,y:260,r:90,unlocked:true,hint:'An ancient road sealed by old ash.'},{id:'ember_grove',name:'Ember Grove',x:870,y:570,r:120,unlocked:true,hint:'Warm roots hide fragments of the ember.'},{id:'hollow_ruins',name:'Hollow Ruins',x:1160,y:280,r:125,unlocked:false,hint:'A broken district full of echoes.'},{id:'starless_path',name:'Starless Path',x:1440,y:610,r:145,unlocked:false,hint:'The road beyond the old kingdom.'}];
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function worldScale(){return Math.min(W/1600,H/900)}function cam(){return{x:clamp(player.x-W/(2*worldScale()),0,1600-W/worldScale()),y:clamp(player.y-H/(2*worldScale()),0,900-H/worldScale())}}function screen(p){const c=cam(),s=worldScale();return{x:(p.x-c.x)*s,y:(p.y-c.y)*s}}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function say(t){toast.textContent=t;toast.classList.add('show');toastTimer=2.2}function log(t){state.log.unshift(t);state.log=state.log.slice(0,8);renderJournal()}
function setQuest(title,desc,obj,count){questTitle.textContent=title;questDesc.textContent=desc;objective.textContent='◈ '+obj;questCount.textContent=count||''}
function currentPlace(){let best=null,bd=1e9;for(const p of places)if(p.unlocked){const d=dist(player,p);if(d<p.r&&d<bd){best=p;bd=d}}return best}
function unlocked(id){return places.find(p=>p.id===id)?.unlocked}function unlock(id){const p=places.find(x=>x.id===id);if(p&&!p.unlocked){p.unlocked=true;say(p.name+' is now open.');log('Unlocked region: '+p.name)}}
function updateQuestUI(){if(state.quest===0)setQuest('A Stranger at the Gate','The sanctuary keeper is waiting near the central fire.','Talk to Lyra','1 / 1');if(state.quest===1)setQuest('The First Spark','Lyra asked you to inspect the sealed gate and recover ember fragments.','Find 3 Ember Shards in Ember Grove',state.shards+' / 3');if(state.quest===2)setQuest('Echoes of the Road','Orren needs help clearing the ruins before the road can open.','Disperse 5 Hollow Echoes',state.echoes+' / 5');if(state.quest===3)setQuest('A Choice in the Dark','The Seer knows what is waking beyond the kingdom.','Speak with the Seer','1 / 1');if(state.quest>=4)setQuest('The Road Remembers','Your choices changed the sanctuary. Explore, gather, rest and uncover what comes next.','Reach the Starless Path',unlocked('starless_path')?'OPEN':'LOCKED');regionLabel.textContent=(currentPlace()?.name||'ASHEN MARCH').toUpperCase()}
function npcById(id){return npcs.find(n=>n.id===id)}
function nearestInteract(){let best=null,bd=62;for(const n of npcs){const d=dist(player,n);if(d<bd){best=n;bd=d}}for(const p of places){const d=dist(player,p);if(d<bd&&p.id!=='sanctuary'){best=p;bd=d}}return best}
function openDialogue(npc){paused=true;dialogue.classList.add('show');speakerName.textContent=npc.name.toUpperCase();speakerRole.textContent=npc.role.toUpperCase();choices.innerHTML='';let text='',opts=[];
if(npc.id==='lyra'){if(state.quest===0){text='You woke with the ember in your hand. I can feel the old seal weakening. Before you leave, I need to know whether you will protect this place.';opts=[['I will help the sanctuary.','help'],['I need answers first.','truth']]}else if(state.quest===1){text=state.shards<3?'The grove still remembers the old fire. Bring me three fragments and I can reopen the road.':'You found them. The ember responds to you now. The gate will not hold forever.';opts=state.shards<3?[['I will search the grove.','close']]:[['Open the road.','finish1']]}else{text=state.flags.truth?'You chose the harder question. That may be exactly why the Seer noticed you.':'The sanctuary is changing around you. Do not mistake quiet for safety.';opts=[['Thank you, Lyra.','close']]}}
if(npc.id==='orren'){text=state.quest<2?'The road is quiet, but the ruins are not. Come back when Lyra sends you.':state.quest===2?'Those echoes are memories given shape. Disperse five and I will show you the old road.':'The ruins are calmer now. Keep exploring; the world has more to say.';opts=[['Leave.','close']]}
if(npc.id==='seer'){if(state.quest===3){text='There are two futures in the ash. One keeps the sanctuary safe. The other follows the truth beyond the kingdom. Neither is free.';opts=[['Protect the sanctuary.','protect'],['Follow the truth.','truth']]}else{text=state.flags.truth?'Then you chose the path beyond the veil. The road will answer you.':'Protection is not the same as peace.';opts=[['Leave.','close']]}}
dialogueText.textContent=text;for(const [label,id] of opts){const b=document.createElement('button');b.className='choice';b.textContent=label;b.onclick=()=>choose(npc,id);choices.appendChild(b)}}
function choose(npc,id){if(id==='help'){state.rep.lyra+=5;state.quest=1;log('Lyra entrusted you with the first ember search.');say('New objective: find Ember Shards');closeDialogue();return}if(id==='truth'){state.flags.truth=true;state.rep[npc.id]=(state.rep[npc.id]||0)+8;if(npc.id==='lyra'){state.quest=1;say('Lyra accepts your questions. The grove is still the first step.')}else{state.quest=4;unlock('starless_path');say('A hidden road has revealed itself.')}closeDialogue();return}if(id==='protect'){state.rep.seer+=6;state.quest=4;unlock('starless_path');log('You chose to protect the sanctuary. The road remains open, but its meaning has changed.');say('The sanctuary is protected. The road is still yours to explore.');closeDialogue();return}if(id==='finish1'){state.quest=2;state.flags.gate=true;unlock('hollow_ruins');log('The Ashen Gate opens. Orren asks for help at the ruins.');say('Region unlocked: Hollow Ruins');closeDialogue();return}closeDialogue()}
function closeDialogue(){dialogue.classList.remove('show');paused=false;updateQuestUI()}
function interact(){const x=nearestInteract();if(!x)return;if(x.id&&npcById(x.id)){openDialogue(x);return}if(x.id==='ember_grove'){if(state.quest===1&&state.shards<3){state.shards++;meta.discoveries++;rollItem(state.shards+state.day);meta.daily.value++;meta.collection.add('first_spark');meta.seasonXP+=30;burst(x.x+(Math.random()-.5)*60,x.y+(Math.random()-.5)*60,12,'#e6a067');say('Ember Shard recovered · '+state.shards+'/3');log('Recovered an Ember Shard from the grove.')}else say('The grove is warm, but there is nothing more to gather right now.');return}if(x.id==='hollow_ruins'){if(state.quest>=2){spawnEchoes(3);say('Hollow Echoes emerged from the ruins.')}else say('The ruins are sealed.');return}}
function spawnEchoes(n){for(let i=0;i<n;i++)enemies.push({x:1080+Math.random()*160,y:220+Math.random()*150,r:18,hp:42,max:42,hit:0})}
function attack(){if(paused||ended||player.attackCd>0)return;player.attack=.22;player.attackCd=.32;player.angle=Math.atan2(mouse.y-H/2,mouse.x-W/2);for(const e of enemies)if(dist(player,e)<82){e.hp-=28;e.hit=.14;burst(e.x,e.y,8,'#d67b4c');if(e.hp<=0){state.echoes++;meta.weekly.value++;rollItem(state.echoes+state.shards+7);meta.seasonXP+=45;state.coins+=8;log('A Hollow Echo dispersed.');say('+8 Ashen Coins')}}enemies=enemies.filter(e=>e.hp>0);if(state.quest===2&&state.echoes>=5){state.quest=3;state.flags.ruins=true;unlock('starless_path');say('The ruins fall silent. The Seer is waiting.');log('Orren says the road to the Seer is open.')}}
function dodge(){if(player.inv>0||player.stamina<18)return;player.stamina-=18;player.inv=.32;let x=(keys.d?1:0)-(keys.a?1:0),y=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(x,y)||1;player.x+=x/l*75;player.y+=y/l*75;burst(player.x,player.y,8,'#9c8d7d')}
function burst(x,y,n,col){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*120;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.45,max:.7,size:1+Math.random()*3,col})}}
function playerMove(dt){let x=(keys.d?1:0)-(keys.a?1:0),y=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(x,y)||1;if(x||y){const sp=player.speed*(keys.shift&&player.stamina>0?1.45:1);player.x+=x/l*sp*dt;player.y+=y/l*sp*dt;if(keys.shift)player.stamina-=16*dt}else player.stamina+=24*dt;player.stamina=clamp(player.stamina,0,100);player.x=clamp(player.x,35,1565);player.y=clamp(player.y,35,865);if(player.inv>0)player.inv-=dt;if(player.attack>0)player.attack-=dt;if(player.attackCd>0)player.attackCd-=dt}
function enemyAI(dt){for(const e of enemies){e.hit-=dt;const a=Math.atan2(player.y-e.y,player.x-e.x),d=dist(player,e);if(d<270){e.x+=Math.cos(a)*45*dt;e.y+=Math.sin(a)*45*dt}if(d<32&&player.inv<=0){player.hp-=8;player.inv=.3;say('The echoes hurt you. Dodge or pulse them away.');if(player.hp<=0)lose()}}}
function worldDay(){const phase=Math.floor((time%90)/30),names=['DAWN','DAY','DUSK'];dayLabel.textContent='DAY '+state.day+' · '+names[phase]}
function camp(){if(dist(player,{x:400,y:420})<100){state.day++;meta.questsDone+=state.quest>0?1:0;meta.seasonXP+=25;player.hp=100;player.stamina=100;log('You rested beneath the sanctuary light. Day '+state.day+' begins.');say('Rested. Day '+state.day+' begins.') }else say('Find a safe place at the sanctuary to rest.')}

// ===== META PROGRESSION / SOCIAL LAYER =====
const meta={menu:$('metaMenu'),content:$('metaContent'),tab:'rank',rank:'total',seasonXP:0,achievements:new Set(),collection:new Set(),questsDone:0,steps:0,discoveries:0,sessionStart:Date.now(),daily:{name:'Ember Survey',goal:3,value:0,reward:30},weekly:{name:'Echo Archivist',goal:5,value:0,reward:120}};

const itemCatalog=[
{id:'ashen-core',name:'Ashen Core',type:'Relic',rarity:'Rare',icon:'◇',base:38,attrs:['+8 Ember','+5 Ward','+3 Luck']},
{id:'veil-mantle',name:'Veil Mantle',type:'Armor',rarity:'Epic',icon:'◈',base:62,attrs:['+14 Vitality','+7 Ward','+4 Haste']},
{id:'ember-sigil',name:'Ember Sigil',type:'Trinket',rarity:'Legendary',icon:'✦',base:95,attrs:['+18 Ember','+9 Luck','+6 Haste']},
{id:'quiet-tea',name:'Quiet Tea',type:'Consumable',rarity:'Common',icon:'◌',base:12,attrs:['Restore 20 HP','Calm +1']},
{id:'star-dust',name:'Star Dust',type:'Material',rarity:'Uncommon',icon:'✧',base:24,attrs:['Crafting +1','Value +12']},
{id:'map-fragment',name:'Old Map Fragment',type:'Quest Item',rarity:'Mythic',icon:'▱',base:120,attrs:['Reveal +1','Lore +8']}
];
const inventory=[{...itemCatalog[0],roll:1},{...itemCatalog[3],roll:1},{...itemCatalog[4],roll:2}];
function rollItem(seed){const item=itemCatalog[(seed+inventory.length*3)%itemCatalog.length];const roll=1+(seed%4);const found={...item,roll,attrs:item.attrs.map((a,i)=>i===0?a+' · '+(roll*2)+'%':a)};inventory.push(found);meta.collection.add(item.id);meta.seasonXP+=item.base*roll;return found}
function itemScore(){return inventory.reduce((s,i)=>s+i.base*i.roll,0)}
function crownTitle(rank){return rank===1?'Crown Incumbent':rank===2?'Royal Challenger':rank===3?'High Regent':rank===4?'Crown Vanguard':rank===5?'Crown Keeper':rank<=10?'Crown Elite':'Ashen Adventurer'}
function totalScore(){const s=playerScores();return s.explorer+s.quest*8+s.collection*2+s.reputation*3+Math.max(0,5000-s.speed)+itemScore()*4+meta.seasonXP}
const rankSeeds={explorer:[['Astra',9840],['Morrow',8420],['CinderFox',7310],['Rin',6450],['Vey',5920]],quest:[['Morrow',74],['Astra',63],['Rin',57],['CinderFox',51],['Vey',48]],collection:[['CinderFox',96],['Astra',88],['Morrow',82],['Vey',71],['Rin',69]],reputation:[['Astra',480],['LyraFan',420],['Morrow',390],['Rin',355],['Vey',330]],speed:[['Morrow',812],['CinderFox',901],['Astra',1044],['Rin',1190],['Vey',1302]]};
const achievements=[
 ['first_spark','First Spark','Recover your first Ember Shard',()=>state.shards>=1],
 ['open_road','Open Road','Unlock your first new region',()=>state.flags.gate],
 ['echo_archivist','Echo Archivist','Disperse five Hollow Echoes',()=>state.echoes>=5],
 ['trusted','A Name Among Friends','Earn reputation with an NPC',()=>Object.values(state.rep).some(v=>v>=5)],
 ['daywalker','Daywalker','Rest and begin a new day',()=>state.day>1],
 ['pathfinder','Pathfinder','Reach the Starless Path',()=>state.quest>=4]
];
const collectionItems=['Ember Shard','Sanctuary Sigil','Ashen Map Fragment','Echo Memory','Seer’s Mark','Old Kingdom Coin'];
function awardXP(n){meta.seasonXP+=n;state.coins+=Math.max(1,Math.floor(n/5));checkAchievements();renderMeta()}
function checkAchievements(){for(const a of achievements)if(a[3]()&&!meta.achievements.has(a[0])){meta.achievements.add(a[0]);meta.collection.add(a[0]);awardToast('Achievement unlocked: '+a[1]);}}
function awardToast(t){say(t);log(t)}
function playerScores(){const rep=Object.values(state.rep).reduce((a,b)=>a+b,0);return{explorer:meta.discoveries*700+state.shards*420+meta.steps*2,quest:meta.questsDone*1000+state.quest*650,reputation:rep*10,collection:meta.collection.size*500+state.shards*100,speed:Math.floor((Date.now()-meta.sessionStart)/1000)}}
function leaderboardRows(type){if(type==='total'){const rows=[['Astra',14280],['Morrow',12640],['CinderFox',11320],['Rin',10180],['Vey',9460],['Noct',8720],['Lumen',8140],['AshWalker',7690]];rows.push(['YOU',totalScore()]);return rows.sort((a,b)=>b[1]-a[1])}const rows=[...rankSeeds[type]];const score=playerScores()[type];rows.push(['YOU',score]);rows.sort((a,b)=>type==='speed'?a[1]-b[1]:b[1]-a[1]);return rows}
function renderMeta(){if(!meta.menu.classList.contains('show'))return;const tabs={rank:'rank',achievements:'achievements',challenges:'challenges',collection:'collection'};if(meta.tab==='rank'){const types=[['total','TOTAL'],['explorer','EXPLORER'],['quest','QUESTS'],['collection','COLLECTION'],['reputation','REPUTATION'],['speed','SPEED']];const t=meta.rank;meta.content.innerHTML='<div class="rank-filter">'+types.map(x=>'<button class="'+(x[0]===t?'active':'')+'" data-rank="'+x[0]+'">'+x[1]+'</button>').join('')+'</div><div class="meta-list">'+leaderboardRows(t).slice(0,8).map((r,i)=>'<div class="rank-row '+(r[0]==='YOU'?'me':'')+'"><span class="rank">#'+(i+1)+'</span><span><b>'+r[0]+'</b><span class="sub">'+(r[0]==='YOU'?'Your current beta score':'Seasonal adventurer')+(t==='total'?'<span class="rank-crown"><span class="crown-icon">♛</span>'+crownTitle(i+1)+'</span>':'')+'</span></span><span class="score">'+r[1].toLocaleString()+'</span></div>').join('')+'</div>';meta.content.querySelectorAll('[data-rank]').forEach(b=>b.onclick=()=>{meta.rank=b.dataset.rank;renderMeta()})}
if(meta.tab==='achievements'){meta.content.innerHTML='<div class="meta-list">'+achievements.map(a=>{const ok=meta.achievements.has(a[0]);return '<div class="achievement-row"><span class="badge">'+(ok?'UNLOCKED':'LOCKED')+'</span><span><b>'+a[1]+'</b><span class="sub">'+a[2]+'</span></span><span>'+ (ok?'✓':'—')+'</span></div>'}).join('')+'</div>'}
if(meta.tab==='challenges'){const d=meta.daily,w=meta.weekly;meta.content.innerHTML='<div class="meta-list"><div class="challenge-row"><span class="badge">DAILY</span><span><b>'+d.name+'</b><span class="sub">Survey ember sites · resets every day</span><div class="progress"><i style="width:'+Math.min(100,d.value/d.goal*100)+'%"></i></div></span><span>'+d.value+'/'+d.goal+' · +'+d.reward+'</span></div><div class="challenge-row"><span class="badge">WEEKLY</span><span><b>'+w.name+'</b><span class="sub">Disperse echoes · resets every week</span><div class="progress"><i style="width:'+Math.min(100,w.value/w.goal*100)+'%"></i></div></span><span>'+w.value+'/'+w.goal+' · +'+w.reward+'</span></div></div>'}
if(meta.tab==='items'){const campaignUniqueItems=typeof ASHEN_CAMPAIGN!=='undefined'?ASHEN_CAMPAIGN.flatMap(ch=>ch.items.map(name=>({name,chapter:ch.id,type:'Story Unique',rarity:ch.id===10?'Mythic':ch.id>=7?'Legendary':ch.id>=4?'Epic':'Rare',icon:'✦',base:50+ch.id*10,roll:1,attrs:['Chapter '+String(ch.id).padStart(2,'0'),'Story-bound','Collection item']}))):[];const visibleItems=[...inventory,...campaignUniqueItems];meta.content.innerHTML='<div class="meta-list">'+visibleItems.slice().reverse().map(i=>'<div class="item-row"><div class="item-icon">'+i.icon+'</div><div><div class="item-name">'+i.name+' <span class="rarity '+i.rarity+'">'+i.rarity+'</span></div><div class="item-type">'+i.type+' · item power '+(i.base*i.roll)+'</div><div class="affixes">'+i.attrs.map(a=>'<span class="affix">'+a+'</span>').join('')+'</div></div><span class="badge">x'+i.roll+'</span></div>').join('')+'</div>'}if(meta.tab==='collection'){meta.content.innerHTML='<div class="meta-list">'+collectionItems.map((x,i)=>{const ok=meta.collection.has(achievements[i]?.[0])||i<state.shards;return '<div class="collection-row"><span class="badge">'+(ok?'FOUND':'???')+'</span><span><b>'+ (ok?x:'Unknown Relic')+'</b><span class="sub">'+(ok?'Added to your archive':'Discover this item in the world')+'</span></span><span>'+(ok?'✓':'')+'</span></div>'}).join('')+'</div>'}}
document.querySelectorAll('.meta-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.meta-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');meta.tab=b.dataset.meta;renderMeta()});
$('closeMeta').onclick=()=>{meta.menu.classList.remove('show');paused=false};
function openMeta(){if(dialogue.classList.contains('show'))return;paused=true;meta.menu.classList.add('show');renderMeta()}

let uiClock=0;let frameCount=0;function update(dt){uiClock+=dt;frameCount++;time+=dt;playerMove(dt);enemyAI(dt);worldDay();let near=null,place=null;if(uiClock>=0.1){near=nearestInteract();interaction.classList.toggle('show',!!near);if(near)interaction.querySelector('span').textContent=near.name||'Interact';place=currentPlace();if(place){locationName.textContent=place.name.toUpperCase();locationHint.textContent=place.hint}else{locationName.textContent='ASHEN MARCH';locationHint.textContent='The road between stories.'}}if(state.quest===2&&enemies.length===0&&state.echoes<5&&state.flags.ruins)spawnEchoes(2);if(state.quest>=4&&currentPlace()?.id==='starless_path')win();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt}if(particles.length>180)particles.splice(0,particles.length-180);particles=particles.filter(p=>p.life>0);if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)toast.classList.remove('show')}if(uiClock>=0.1){uiClock=0;updateQuestUI();$('playerHp').style.width=player.hp+'%';$('stamina').style.width=player.stamina+'%';$('coins').textContent=state.coins+' ASHEN';$('level').textContent='LV '+(1+Math.floor((state.shards+state.echoes)/4));$('status').textContent=paused?'PAUSED':enemies.length?'THREAT NEARBY':'EXPLORING'}}
function draw(){ctx.clearRect(0,0,W,H);const s=worldScale(),c=cam();ctx.fillStyle='#0a0908';ctx.fillRect(0,0,W,H);ctx.save();ctx.scale(s,s);ctx.translate(-c.x,-c.y);ctx.fillStyle='rgba(100,48,28,.10)';ctx.fillRect(c.x,c.y,W/s,H/s);drawGrid(c.x,c.y,W/s,H/s);for(const p of places)drawPlace(p);for(const n of npcs)drawNpc(n);drawNodes();for(const e of enemies)drawEnemy(e);drawPlayer();ctx.restore()}
function drawGrid(x,y,w,h){ctx.strokeStyle='rgba(143,99,69,.07)';ctx.lineWidth=1;for(let i=Math.floor(x/80)*80;i<x+w;i+=80){ctx.beginPath();ctx.moveTo(i,y);ctx.lineTo(i,y+h);ctx.stroke()}for(let j=Math.floor(y/80)*80;j<y+h;j+=80){ctx.beginPath();ctx.moveTo(x,j);ctx.lineTo(x+w,j);ctx.stroke()}}
function drawPlace(p){ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=p.unlocked?1:.3;ctx.strokeStyle=p.id==='sanctuary'?'#b9855f':'#684b39';ctx.fillStyle=p.id==='sanctuary'?'rgba(173,104,57,.12)':'rgba(90,60,43,.1)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4+time*.02;ctx.beginPath();ctx.moveTo(Math.cos(a)*p.r*.78,Math.sin(a)*p.r*.78);ctx.lineTo(Math.cos(a)*p.r*.94,Math.sin(a)*p.r*.94);ctx.stroke()}ctx.fillStyle='#b7a99a';ctx.font='600 16px Cormorant Garamond';ctx.textAlign='center';ctx.fillText(p.name,0,p.r+25);ctx.restore()}
function drawNpc(n){ctx.save();ctx.translate(n.x,n.y);ctx.fillStyle=n.color;ctx.shadowBlur=18;ctx.shadowColor=n.color;ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#e6d3c1';ctx.stroke();ctx.fillStyle='#160f0c';ctx.beginPath();ctx.arc(-5,-2,2,0,Math.PI*2);ctx.arc(5,-2,2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d2c3b5';ctx.font='600 15px Cormorant Garamond';ctx.textAlign='center';ctx.fillText(n.name,0,-27);if((state.quest===0&&n.id==='lyra')||(state.quest===3&&n.id==='seer')){ctx.fillStyle='#e3a06e';ctx.font='700 18px DM Sans';ctx.fillText('!',0,-48)}ctx.restore()}
function drawNodes(){if(state.quest!==1)return;for(let i=0;i<3;i++){const x=850+i*35,y=555+(i%2)*28;ctx.fillStyle='#db8a52';ctx.shadowBlur=18;ctx.shadowColor='#db8a52';ctx.beginPath();ctx.arc(x,y,6+Math.sin(time*3+i)*2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.globalAlpha=e.hit>0?.55:1;ctx.fillStyle='#34243c';ctx.strokeStyle='#9873aa';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#d4a5e2';ctx.beginPath();ctx.arc(-6,-3,2.5,0,Math.PI*2);ctx.arc(6,-3,2.5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.globalAlpha=player.inv>0?.55:1;ctx.fillStyle='#e0cdbb';ctx.strokeStyle='#9a6b4c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#d47740';ctx.beginPath();ctx.arc(9,0,4,0,Math.PI*2);ctx.fill();ctx.restore()}
function renderJournal(tab='story'){if(tab==='story')journalBody.innerHTML=state.log.map(x=>'<div class="journal-line">◈ '+x+'</div>').join('');if(tab==='people')journalBody.innerHTML=npcs.map(n=>'<div class="journal-line"><b>'+n.name+' · '+n.role+'</b>Reputation: '+state.rep[n.id]+'</div>').join('');if(tab==='world')journalBody.innerHTML=places.map(p=>'<div class="journal-line"><b>'+p.name+'</b>'+(p.unlocked?'Accessible':'Still sealed')+'</div>').join('')}if(tab==='campaign')journalBody.innerHTML='<div class="campaign-grid">'+ASHEN_CAMPAIGN.map(ch=>'<article class="chapter-card '+(ch.id===1?'active':'')+'"><div class="num">CHAPTER '+String(ch.id).padStart(2,'0')+' · '+ch.theme.toUpperCase()+'</div><h3>'+ch.title+'</h3><p>'+ch.summary+'</p><div class="chapter-meta"><span>'+ch.region+'</span><span>'+ch.activities.length+' activities</span><span>'+ch.items.length+' unique items</span></div><div class="story-items">'+ch.items.map(i=>'<span>'+i+'</span>').join('')+'</div><div class="campaign-detail"><strong>Choice:</strong> '+ch.choice+'</div></article>').join('')+'</div>'}
document.querySelectorAll('.journal-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.journal-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderJournal(b.dataset.tab)});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='escape'&&!dialogue.classList.contains('show')){if(meta.menu.classList.contains('show')){meta.menu.classList.remove('show');paused=false;return}paused=!paused;pause.classList.toggle('show',paused)}if(k==='e'&&!paused&&!ended)interact();if(k==='k'&&!paused&&!ended){openMeta()}if(k==='j'&&!paused&&!ended){journal.classList.toggle('open');renderJournal()}if(k==='m'&&!paused&&!ended)say('Map: '+places.filter(p=>p.unlocked).map(p=>p.name).join(' · '));if(k===' '&&!paused&&!ended)dodge();if(k==='c'&&!paused&&!ended)camp()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top});canvas.addEventListener('mousedown',e=>{if(e.button===0)attack()});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('closeDialogue').onclick=closeDialogue;$('resume').onclick=()=>{paused=false;pause.classList.remove('show')};$('restart').onclick=()=>location.reload();
function lose(){ended=true;result.classList.add('show');$('resultTitle').textContent='The ember goes quiet.';$('resultText').textContent='The world remains. Restart the story demo to try a different choice.'}function win(){if(ended)return;ended=true;result.classList.add('show');$('resultTitle').textContent='The road remembers you.';$('resultText').textContent='You reached the story branch. This beta now has quests, choices, NPC relationships, exploration, gathering, encounters and world unlocks.'}
function loop(t){const dt=Math.min((t-last)/1000,.033);last=t;if(!paused&&!ended)update(dt);draw();requestAnimationFrame(loop)}renderJournal();updateQuestUI();setTimeout(()=>$('message').classList.add('hidden'),4200);last=performance.now();requestAnimationFrame(loop);