const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const bossHpEl=document.getElementById('bossHp'),bossPoiseEl=document.getElementById('bossPoise'),playerHpEl=document.getElementById('playerHp'),staminaEl=document.getElementById('stamina'),phaseEl=document.getElementById('phase'),statusEl=document.getElementById('status'),message=document.getElementById('message'),pause=document.getElementById('pause'),result=document.getElementById('result'),resultTitle=document.getElementById('resultTitle'),resultText=document.getElementById('resultText');
let W=1200,H=700,dpr=1,last=0,paused=false,ended=false,keys={},mouse={x:600,y:350,down:false,right:false},particles=[],slashes=[],shake=0,elapsed=0,score=0;
const player={x:600,y:545,r:17,hp:100,stamina:100,angle:-Math.PI/2,speed:225,inv:0,guard:0,attack:0,combo:0,comboTimer:0,heavy:0};
const boss={x:600,y:220,r:34,hp:420,maxHp:420,poise:100,maxPoise:100,phase:1,attack:0,cool:1.2,stun:0,flash:0,charge:0,hitCd:0};
function resize(){const rect=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=rect.width;H=rect.height;canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key==='Escape'){paused=!paused;pause.classList.toggle('show',paused)}if(e.key.toLowerCase()==='f'&&!paused&&!ended)player.guard=1;if(e.key===' '&&!paused&&!ended)dodge()});
addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;if(e.key.toLowerCase()==='f')player.guard=0});
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top});
canvas.addEventListener('mousedown',e=>{if(e.button===0){mouse.down=true;light()}if(e.button===2){mouse.right=true;heavy()}});canvas.addEventListener('mouseup',e=>{if(e.button===0)mouse.down=false;if(e.button===2)mouse.right=false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.getElementById('resume').onclick=()=>{paused=false;pause.classList.remove('show')};document.getElementById('restart').onclick=reset;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function burst(x,y,n=12,hot=true){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*150;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.5,max:.75,size:1+Math.random()*3,hot})}}
function hitFlash(x,y,ang,heavy=false){slashes.push({x,y,a:ang,t:0,life:.22,heavy});burst(x,y,heavy?20:9,true);shake=Math.max(shake,heavy?10:5)}
function light(){if(paused||ended||player.attack>0||player.guard||player.stamina<7)return;player.attack=.28;player.heavy=0;player.combo=(player.comboTimer>0?player.combo+1:1)%5;player.comboTimer=.65;player.angle=Math.atan2(mouse.y-player.y,mouse.x-player.x);player.stamina-=7;setTimeout(()=>{if(ended)return;const d=dist(player,boss),a=Math.atan2(boss.y-player.y,boss.x-player.x),delta=Math.abs(Math.atan2(Math.sin(a-player.angle),Math.cos(a-player.angle)));if(d<92&&delta<1.2&&boss.hitCd<=0)damageBoss(28+(player.combo===4?12:0),10,player.combo===4)},100)}
function heavy(){if(paused||ended||player.attack>0||player.guard||player.stamina<22)return;player.attack=.58;player.heavy=.58;player.stamina-=22;player.angle=Math.atan2(mouse.y-player.y,mouse.x-player.x);setTimeout(()=>{if(ended)return;const d=dist(player,boss),a=Math.atan2(boss.y-player.y,boss.x-player.x),delta=Math.abs(Math.atan2(Math.sin(a-player.angle),Math.cos(a-player.angle)));if(d<125&&delta<1.35&&boss.hitCd<=0)damageBoss(55,24,true)},260)}
function dodge(){if(player.inv>0||player.stamina<18)return;player.stamina-=18;player.inv=.34;const dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),a=dx||dy?Math.atan2(dy,dx):player.angle;player.x+=Math.cos(a)*70;player.y+=Math.sin(a)*70;burst(player.x,player.y,8,false)}
function damageBoss(dmg,poise,heavy=false){boss.hp-=dmg;boss.poise-=poise;boss.hitCd=.13;boss.flash=.12;score+=dmg;hitFlash(boss.x,boss.y,Math.atan2(boss.y-player.y,boss.x-player.x),heavy);if(boss.poise<=0){boss.stun=.85;boss.poise=boss.maxPoise;burst(boss.x,boss.y,35,true);statusEl.textContent='WARDEN STAGGERED';score+=60}if(boss.hp<=boss.maxHp*.66&&boss.phase===1){boss.phase=2;boss.cool=.5;phaseEl.textContent='PHASE II';burst(boss.x,boss.y,45,true)}if(boss.hp<=boss.maxHp*.33&&boss.phase===2){boss.phase=3;boss.cool=.2;phaseEl.textContent='PHASE III';burst(boss.x,boss.y,55,true)}if(boss.hp<=0)finish(true)}
function damagePlayer(dmg){if(player.inv>0)return;if(player.guard){player.stamina-=dmg*.55;burst(player.x,player.y,7,false);statusEl.textContent='GUARDED';if(player.stamina<=0){player.guard=0;player.stamina=0;player.inv=.15}}else{player.hp-=dmg;player.inv=.28;burst(player.x,player.y,10,false);shake=9;statusEl.textContent='WOUNDED';if(player.hp<=0)finish(false)}}
function bossAI(dt){if(boss.stun>0){boss.stun-=dt;return}boss.cool-=dt;boss.hitCd-=dt;boss.flash-=dt;const d=dist(player,boss);if(boss.cool<=0){boss.cool=(boss.phase===3?.85:boss.phase===2?1.15:1.45)+Math.random()*.45;if(d<105)boss.attack=.52;else{boss.attack=.72;boss.charge=1}}if(boss.attack>0){boss.attack-=dt;if(boss.attack<.18&&boss.attack>0){const a=Math.atan2(player.y-boss.y,player.x-boss.x);if(d<125&&Math.random()<.22)damagePlayer(boss.phase===3?22:16)}}else{const a=Math.atan2(player.y-boss.y,player.x-boss.x),spd=38+boss.phase*12;boss.x+=Math.cos(a)*spd*dt;boss.y+=Math.sin(a)*spd*dt;if(boss.phase>=2&&Math.random()<dt*.65){const a2=a+(Math.random()-.5)*1.2;particles.push({x:boss.x,y:boss.y,vx:Math.cos(a2)*170,vy:Math.sin(a2)*170,life:1.1,max:1.1,size:7,projectile:true})}}}
function updateProjectiles(dt){for(const p of particles){if(!p.projectile)continue;p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(Math.hypot(p.x-player.x,p.y-player.y)<18&&p.life>0){p.life=0;damagePlayer(10)}}}
function playerMove(dt){let x=(keys.d?1:0)-(keys.a?1:0),y=(keys.s?1:0)-(keys.w?1:0);const l=Math.hypot(x,y)||1;if(x||y){const sprint=keys.shift&&player.stamina>0&&!player.guard,sp=player.speed*(sprint?1.55:1);player.x+=x/l*sp*dt;player.y+=y/l*sp*dt;if(sprint)player.stamina-=20*dt}else player.stamina+=26*dt;player.stamina=clamp(player.stamina,0,100);player.x=clamp(player.x,55,W-55);player.y=clamp(player.y,105,H-70);if(player.inv>0)player.inv-=dt;if(player.attack>0)player.attack-=dt;if(player.comboTimer>0)player.comboTimer-=dt}
function update(dt){elapsed+=dt;playerMove(dt);bossAI(dt);updateProjectiles(dt);for(const p of particles){if(!p.projectile){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt}}particles=particles.filter(p=>p.life>0);for(const s of slashes)s.t+=dt;slashes=slashes.filter(s=>s.t<s.life);shake*=.88;if(!ended){bossHpEl.style.width=(boss.hp/boss.maxHp*100)+'%';bossPoiseEl.style.width=(boss.poise/boss.maxPoise*100)+'%';playerHpEl.style.width=player.hp+'%';staminaEl.style.width=player.stamina+'%';if(player.guard)statusEl.textContent='GUARDING';else if(player.attack>0)statusEl.textContent=player.heavy>0?'HEAVY COMMIT':'ATTACKING';else if(boss.stun>0)statusEl.textContent='OPENING';else statusEl.textContent='READY'}}
function draw(){ctx.save();if(shake>1)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#0b0908';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.48,30,W*.5,H*.48,Math.max(W,H)*.65);g.addColorStop(0,'rgba(137,62,34,.16)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(150,104,74,.13)';ctx.lineWidth=1;for(let r=90;r<Math.max(W,H);r+=85){ctx.beginPath();ctx.arc(W/2,H*.48,r,0,Math.PI*2);ctx.stroke()}for(let i=0;i<12;i++){const a=i*Math.PI/6+elapsed*.02;ctx.beginPath();ctx.moveTo(W/2+Math.cos(a)*70,H*.48+Math.sin(a)*70);ctx.lineTo(W/2+Math.cos(a)*Math.max(W,H),H*.48+Math.sin(a)*Math.max(W,H));ctx.stroke()}for(const p of particles){ctx.globalAlpha=clamp(p.life/(p.max||1),0,1);ctx.fillStyle=p.projectile?'#d66d43':(p.hot?'#df8b55':'#9a8a78');ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;drawBoss();drawPlayer();for(const s of slashes){const k=s.t/s.life;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.globalAlpha=1-k;ctx.strokeStyle=s.heavy?'#f0a36b':'#d77b4a';ctx.lineWidth=s.heavy?7:4;ctx.beginPath();ctx.arc(0,0,s.heavy?80:62,-.9,.9);ctx.stroke();ctx.restore()}ctx.restore()}
function drawBoss(){const pulse=1+Math.sin(elapsed*4)*.035;ctx.save();ctx.translate(boss.x,boss.y);ctx.scale(pulse,pulse);ctx.globalAlpha=.18;ctx.fillStyle='#d36c40';ctx.beginPath();ctx.arc(0,0,62,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=boss.flash>0?'#f3b083':'#2b1a14';ctx.strokeStyle='#a45736';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,boss.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#704635';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-25,-16);ctx.lineTo(-47,-48);ctx.lineTo(-9,-30);ctx.moveTo(25,-16);ctx.lineTo(47,-48);ctx.lineTo(9,-30);ctx.stroke();ctx.fillStyle='#e5a06c';ctx.beginPath();ctx.arc(-12,-4,3,0,Math.PI*2);ctx.arc(12,-4,3,0,Math.PI*2);ctx.fill();if(boss.attack>0){ctx.strokeStyle='#c76a43';ctx.lineWidth=4;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(0,0,60,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.globalAlpha=player.inv>0?.55:1;ctx.fillStyle=player.guard?'#b9855f':'#d7c4ad';ctx.strokeStyle=player.guard?'#efa46f':'#806a57';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#b85d38';ctx.fillRect(13,-2,27,4);ctx.restore();if(player.guard){ctx.strokeStyle='rgba(239,164,111,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x,player.y,34,-.9,.9);ctx.stroke()}}
function finish(win){ended=true;result.classList.add('show');resultTitle.textContent=win?'The ember survives.':'The crown falls silent.';resultText.textContent=win?'Warden defeated in '+elapsed.toFixed(1)+'s · '+score+' combat score':'The Warden remains. Try guarding and dodging instead of trading every hit.';document.getElementById('resultKicker').textContent=win?'TRIAL COMPLETE':'TRIAL FAILED'}
function reset(){Object.assign(player,{x:W/2,y:H*.76,hp:100,stamina:100,angle:-Math.PI/2,inv:0,guard:0,attack:0,combo:0,comboTimer:0,heavy:0});Object.assign(boss,{x:W/2,y:H*.28,hp:420,maxHp:420,poise:100,maxPoise:100,phase:1,attack:0,cool:1.1,stun:0,flash:0,charge:0,hitCd:0});particles=[];slashes=[];elapsed=0;score=0;paused=false;ended=false;phaseEl.textContent='PHASE I';result.classList.remove('show');message.classList.remove('hidden');last=performance.now();requestAnimationFrame(loop)}
function loop(t){if(ended)return;const dt=Math.min((t-last)/1000,.033);last=t;if(!paused)update(dt);draw();requestAnimationFrame(loop)}last=performance.now();requestAnimationFrame(loop);setTimeout(()=>message.classList.add('hidden'),3500);