import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js';

const $=id=>document.getElementById(id);
const canvas=$('game'), scene=new THREE.Scene();
scene.background=new THREE.Color(0x090807); scene.fog=new THREE.Fog(0x090807,20,55);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5)); renderer.outputColorSpace=THREE.SRGBColorSpace;
const camera=new THREE.PerspectiveCamera(55,1,.1,100); camera.position.set(0,4,8);
scene.add(new THREE.HemisphereLight(0xcbb29e,0x090706,1.5));
const sun=new THREE.DirectionalLight(0xffc39d,2.2); sun.position.set(-8,14,7); scene.add(sun);
const world=new THREE.Group(), characters=new THREE.Group(), props=new THREE.Group(), effects=new THREE.Group(); scene.add(world);
world.add(characters,props,effects);

const state={day:1,xp:0,level:1,hp:100,stamina:100,coins:40,shards:0,echoes:0,quest:0,chapter:1,rep:{lyra:0,orren:0,seer:0},flags:{gate:false,truth:false},inventory:[],log:['You wake beneath the sanctuary with an ember glowing in your palm.']};
const keys={}; let yaw=0,pitch=.28,drag=false,lx=0,ly=0,time=0,toastTimer=0,encounter=null;
const player=new THREE.Group(); player.position.set(0,0,7); characters.add(player);

const mat=(c,r=.75,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
const orb=(r,c,glow=false)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),mat(c,.4,.1));if(glow)m.material.emissive=new THREE.Color(c).multiplyScalar(1.5);return m};
const box=(x,y,z,c)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.castShadow=true;return m};
function actor(c,a){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1,6,12),mat(c,.65,.15));body.position.y=1;g.add(body);const head=orb(.34,0xd0b9a5);head.position.y=1.9;g.add(head);const hood=new THREE.Mesh(new THREE.ConeGeometry(.42,.55,8),mat(a));hood.position.y=2.15;g.add(hood);const core=orb(.13,0xff8245,true);core.position.set(0,1.1,.35);g.add(core);return g}
player.add(actor(0x29221d,0x613724)); const cape=box(.75,.9,.12,0x151213);cape.position.set(0,1,-.38);player.add(cape);

const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,80),mat(0x15110f,.98));ground.rotation.x=-Math.PI/2;world.add(ground);
const grid=new THREE.GridHelper(70,35,0x30251f,0x191411);grid.material.opacity=.28;grid.material.transparent=true;world.add(grid);
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);const t=box(.3,1.7,.3,0x34261e);t.position.y=.85;g.add(t);const c=orb(.85,0x26342a);c.position.y=2;g.add(c);props.add(g)}
for(let i=0;i<24;i++){const a=i*1.17;tree(Math.sin(a*1.9)*17,Math.cos(a*1.4)*18,.75+(i%3)*.1)}
function lantern(x,z){const g=new THREE.Group();g.position.set(x,0,z);const p=box(.08,2.2,.08,0x29231f);p.position.y=1.1;g.add(p);const l=orb(.17,0xff8b4c,true);l.position.y=2.3;g.add(l);props.add(g)}
[[-6,-4],[6,-4],[-8,5],[8,5],[0,-10]].forEach(p=>lantern(...p));

const npcs=[
 {id:'lyra',name:'Lyra',role:'Sanctuary Keeper',pos:[-5,-3],c:0x70432f,a:0xb8784d},
 {id:'orren',name:'Orren',role:'Wayfinder',pos:[7,-1],c:0x384456,a:0x6f86a5},
 {id:'seer',name:'The Seer',role:'Keeper of Echoes',pos:[13,-8],c:0x493b63,a:0x9272c4}
].map(n=>{const g=new THREE.Group();g.position.set(n.pos[0],0,n.pos[1]);g.add(actor(n.c,n.a));characters.add(g);return {...n,root:g}});

const nodes=[];
function node(type,x,z,c,label){const g=new THREE.Group();g.position.set(x,0,z);const o=orb(.32,c,true);o.position.y=.5;g.add(o);const r=new THREE.Mesh(new THREE.TorusGeometry(.55,.035,8,24),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.5}));r.rotation.x=Math.PI/2;g.add(r);props.add(g);nodes.push({type,x,z,label,root:g,collected:false})}
node('ember',-10,-6,0xff7040,'Emberleaf');node('ember',-14,2,0xff7040,'Emberleaf');node('echo',10,4,0x9b78dc,'Memory Echo');node('echo',15,2,0x9b78dc,'Memory Echo');node('relic',3,-13,0xd7b36a,'Ancient Relic');

const gates=[['Ashen Gate',0,-16,0],['Hollow Ruins',18,-4,2],['Starless Path',-20,8,4]].map(([name,x,z,unlock])=>{const g=new THREE.Group();g.position.set(x,0,z);const r=new THREE.Mesh(new THREE.TorusGeometry(2,.17,10,32),new THREE.MeshStandardMaterial({color:0x5d3b2d,emissive:0x281008}));r.rotation.x=Math.PI/2;g.add(r);props.add(g);return{name,x,z,unlock,root:g}});

let enemies=[];
function spawnEnemy(){if(enemies.length)return;const g=new THREE.Group();g.position.copy(player.position).add(new THREE.Vector3(5,0,-4));const b=orb(.48,state.quest>=3?0x613b31:0x684a79,true);b.position.y=1;g.add(b);const e1=orb(.06,0xffc48b,true),e2=e1.clone();e1.position.set(-.13,1.08,.35);e2.position.set(.13,1.08,.35);g.add(e1,e2);characters.add(g);encounter={root:g,hp:state.quest>=3?70:30};toastMsg('A wandering encounter has appeared.')}
function xp(n){state.meta.mastery+=Math.max(1,Math.floor(n/5));state.meta.points+=Math.max(1,Math.floor(n/20));state.xp+=n;const need=100+state.level*55;if(state.xp>=need){state.xp-=need;state.level++;state.hp=100;toastMsg('Level up — Emberbound Lv '+state.level)}}
function item(name,type,rarity,attrs){state.meta.renown+=rarity==='Legendary'?4:rarity==='Epic'?3:2;state.meta.points+=1;state.inventory.push({name,type,rarity,attrs});state.log.unshift('Collected '+name+'.')}
function toastMsg(t){$('toast').textContent=t;$('toast').classList.add('show');toastTimer=3}
function setQuest(){const q=state.quest, title=$('questTitle'),desc=$('questDesc'),obj=$('objective'),count=$('questCount');if(q===0){title.textContent='A Stranger at the Gate';desc.textContent='Meet Lyra and choose what kind of traveler you will become.';obj.textContent='◈ Talk to Lyra';count.textContent='1 / 1'}else if(q===1){title.textContent='Embers in the Grove';desc.textContent='Gather living embers beyond the sanctuary.';obj.textContent='◈ Collect Emberleaf';count.textContent=state.shards+' / 2'}else if(q===2){title.textContent='The Road Opens';desc.textContent='Orren knows how to cross the old gate.';obj.textContent='◈ Speak with Orren';count.textContent='1 / 1'}else if(q===3){title.textContent='Echoes of Hollow';desc.textContent='Recover memory echoes from the eastern ruins.';obj.textContent='◈ Recover Memory Echoes';count.textContent=state.echoes+' / 2'}else if(q===4){title.textContent='A Choice in the Ash';desc.textContent='Return to Lyra. Your next decision will alter the road.';obj.textContent='◈ Return to Lyra';count.textContent='1 / 1'}else{title.textContent='The Road Continues';desc.textContent='Your first chapter has changed the world.';obj.textContent='◈ Explore';count.textContent='COMPLETE'}$('regionLabel').textContent=region().toUpperCase()}
function region(){const p=player.position;return p.z<-11?'Ember Grove':p.x>11?'Hollow Ruins':p.x<-13?'Starless Path':'Sanctuary'}
function nearby(){let best=null,d=3;for(const n of npcs){const x=n.root.position.distanceTo(player.position);if(x<d){d=x;best={k:'npc',n}}}for(const n of nodes)if(!n.collected){const x=n.root.position.distanceTo(player.position);if(x<d){d=x;best={k:'node',n}}}for(const g of gates){const x=g.root.position.distanceTo(player.position);if(x<d){d=x;best={k:'gate',n:g}}}if(encounter){const x=encounter.root.position.distanceTo(player.position);if(x<d)best={k:'enemy',n:encounter}}return best}
function dialogue(n,text,opts){$('dialogue').classList.add('show');$('speakerName').textContent=n.name.toUpperCase();$('speakerRole').textContent=n.role.toUpperCase();$('dialogueText').textContent=text;const c=$('choices');c.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.textContent=o.label;b.onclick=()=>{o.fn();$('dialogue').classList.remove('show')};c.appendChild(b)})}
function interact(){const a=nearby();if(!a)return;if(a.k==='npc'){const n=a.n;if(n.id==='lyra'&&state.quest===0)dialogue(n,'You carry the last ember. I can open the sanctuary road, but I need to know your intent.',[{label:'Protect the sanctuary',fn:()=>{state.rep.lyra++;state.quest=1;xp(25);item('Sanctuary Sigil','Relic','Rare',['Ward','Story Bound']);toastMsg('Quest started: gather Emberleaf');setQuest()}},{label:'Ask for the truth',fn:()=>{state.rep.lyra+=2;state.flags.truth=true;state.quest=1;xp(30);item('Emberleaf Charm','Trinket','Epic',['Lore','Luck']);toastMsg('Lyra respects your questions');setQuest()}}]);else if(n.id==='orren'&&state.quest===2)dialogue(n,'The old gate is unstable. I can show you the safe route, but the road beyond it is yours to discover.',[{label:'Trust Orren',fn:()=>{state.rep.orren+=2;state.quest=3;state.flags.gate=true;xp(35);toastMsg('Ashen Gate opened');setQuest()}},{label:'Study his map',fn:()=>{state.rep.orren++;state.quest=3;state.flags.gate=true;item('Tideglass Compass','Relic','Rare',['Discovery']);toastMsg('You found a hidden route');setQuest()}}]);else if(n.id==='lyra'&&state.quest===4)dialogue(n,'The road is open. What should the sanctuary become?',[{label:'Open it to everyone',fn:()=>{state.quest=5;state.rep.lyra++;xp(70);item('Crownless Signet','Quest Item','Legendary',['Legacy']);toastMsg('Your choice changed the sanctuary');setQuest()}},{label:'Keep it hidden',fn:()=>{state.quest=5;state.rep.lyra+=2;xp(70);item('Hearth Memory','Relic','Legendary',['Reputation']);toastMsg('The sanctuary remains hidden');setQuest()}}]);else toastMsg(n.name+': The road remembers every choice.')}
else if(a.k==='node'){const n=a.n;n.collected=true;n.root.visible=false;if(n.type==='ember'){state.shards++;xp(18);item(n.label,'Material',state.shards>=2?'Rare':'Uncommon',['Crafting','Ember']);toastMsg('Emberleaf collected');if(state.quest===1&&state.shards>=2)state.quest=2}else if(n.type==='echo'){state.echoes++;xp(22);item(n.label,'Quest Item','Epic',['Memory','Lore']);toastMsg('Memory Echo recovered');if(state.quest===3&&state.echoes>=2)state.quest=4}else{state.coins+=35;xp(30);item('Ancient Relic','Relic','Legendary',['Collection','Value']);toastMsg('Hidden relic discovered')}setQuest()}
else if(a.k==='gate'){if(state.quest<a.n.unlock){toastMsg(a.n.name+' is sealed by the story.');return}toastMsg(a.n.name+' discovered — '+region())}
else if(a.k==='enemy')pulse()}
function pulse(){if(!encounter||state.stamina<15)return;state.stamina-=15;encounter.hp-=18+state.level*2;const g=new THREE.Group();g.position.copy(player.position);for(let i=0;i<8;i++){const o=orb(.05,0xff8a4d,true),a=i*Math.PI/4;o.position.set(Math.cos(a),.8,Math.sin(a));g.add(o)}effects.add(g);setTimeout(()=>g.removeFromParent(),280);if(encounter.hp<=0){encounter.root.removeFromParent();enemies=[];state.coins+=25;xp(35);item('Ashen Wisp Fragment','Relic','Rare',['Encounter Drop']);encounter=null;toastMsg('Encounter cleared — loot recovered')}}
function move(dt){if(dodgeCooldown>0)dodgeCooldown-=dt;let x=(keys.KeyD?1:0)-(keys.KeyA?1:0),z=(keys.KeyS?1:0)-(keys.KeyW?1:0);const l=Math.hypot(x,z);if(!l){state.stamina=Math.min(100,state.stamina+22*dt);return}x/=l;z/=l;const d=new THREE.Vector3(x,0,z).applyAxisAngle(new THREE.Vector3(0,1,0),yaw),run=keys.ShiftLeft||keys.ShiftRight,s=run?7.2:4.7;player.position.addScaledVector(d,s*dt);player.rotation.y=Math.atan2(d.x,d.z);state.stamina=Math.max(0,state.stamina+(run?-9:16)*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-28,28);player.position.z=THREE.MathUtils.clamp(player.position.z,-24,22)}
function updateCamera(dt){const target=player.position.clone().add(new THREE.Vector3(0,1.15,0)),back=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw));const pos=target.clone().addScaledVector(back,7.2).add(new THREE.Vector3(0,3.2+pitch*2,0));camera.position.lerp(pos,1-Math.pow(.001,dt));camera.lookAt(target)}
function tick(dt){time+=dt;move(dt);updateCamera(dt);for(const n of nodes)if(!n.collected)n.root.rotation.y+=dt;for(const e of enemies){e.root.rotation.y+=dt;e.root.position.y=1+Math.sin(time*2)*.2;if(e.root.position.distanceTo(player.position)<2.3)state.hp=Math.max(0,state.hp-5*dt)}if(state.hp<=0){state.hp=100;player.position.set(0,0,7);toastMsg('You returned to the sanctuary')}$('playerHp').style.width=state.hp+'%';$('stamina').style.width=state.stamina+'%';$('level').textContent='LV '+state.level;$('coins').textContent=state.coins+' ASHEN';$('status').textContent=enemies.length?'ENCOUNTER':(keys.ShiftLeft||keys.ShiftRight?'SPRINTING':'EXPLORING');$('locationName').textContent=region().toUpperCase();$('locationHint').textContent=region()==='Sanctuary'?'A safe place beneath the last light.':region()==='Ember Grove'?'Living embers grow beyond the old road.':region()==='Hollow Ruins'?'Forgotten memories drift through the ruins.':'A road reserved for later chapters.';const a=nearby();$('interaction').classList.toggle('show',!!a);if(a)$('interaction').querySelector('span').textContent=a.k==='npc'?'Talk':a.k==='node'?'Gather':a.k==='gate'?'Enter':'Pulse';$('dayLabel').textContent='DAY '+state.day+' · '+(time%30<10?'DAWN':time%30<20?'DAY':'DUSK')}
function renderJournal(tab='story'){if(tab==='story')$('journalBody').innerHTML=state.log.slice(0,12).map(x=>'<div class="journal-line">◈ '+x+'</div>').join('');if(tab==='people')$('journalBody').innerHTML=npcs.map(n=>'<div class="journal-line"><b>'+n.name+' · '+n.role+'</b>Reputation: '+state.rep[n.id]+'</div>').join('');if(tab==='world')$('journalBody').innerHTML=gates.map(g=>'<div class="journal-line"><b>'+g.name+'</b> '+(state.quest>=g.unlock?'Accessible':'Sealed by story')+'</div>').join('');if(tab==='campaign')$('journalBody').innerHTML='<div class="campaign-grid">'+(window.ASHEN_CAMPAIGN||[]).map(ch=>'<article class="chapter-card '+(ch.id===state.chapter?'active':'')+'"><div class="num">CHAPTER '+String(ch.id).padStart(2,'0')+' · '+ch.theme.toUpperCase()+'</div><h3>'+ch.title+'</h3><p>'+ch.summary+'</p><div class="chapter-meta"><span>'+ch.region+'</span><span>'+ch.activities.length+' activities</span><span>'+ch.items.length+' unique items</span></div><div class="story-items">'+ch.items.map(i=>'<span>'+i+'</span>').join('')+'</div></article>').join('')+'</div>'}
function archive(){const m=$('metaMenu');m.classList.add('show');const next=100+state.level*40,rank=state.meta.renown>=40?'CROWNBOUND':state.meta.renown>=20?'PATHFINDER':state.meta.renown>=8?'WAYFARER':'EMBERBOUND';$('metaContent').innerHTML='<div class="meta-dashboard"><div class="meta-hero"><span>LEGACY RANK</span><strong>'+rank+'</strong><small>Permanent progression · '+state.meta.legacy+' Legacy</small></div><div class="meta-stats"><div><b>'+state.meta.mastery+'</b><span>Mastery XP</span></div><div><b>'+state.meta.renown+'</b><span>Renown</span></div><div><b>'+state.meta.points+'</b><span>Growth Points</span></div><div><b>'+state.inventory.length+'</b><span>Discoveries</span></div></div><div class="meta-progress"><div><span>LEVEL '+state.level+'</span><b>'+state.xp+' / '+next+' XP</b></div><i style="width:'+Math.min(100,state.xp/next*100)+'%"></i></div><div class="meta-goals"><article><span>WEEKLY PATH</span><b>Discover 5 locations</b><small>'+Math.min(5,state.inventory.length)+' / 5 · Reward: +3 Renown</small></article><article><span>MASTER STUDY</span><b>Collect 3 story items</b><small>'+Math.min(3,state.inventory.length)+' / 3 · Reward: +2 Growth Points</small></article><article><span>LEGACY</span><b>Complete Chapter 01</b><small>'+(state.quest>=5?'Complete · Legacy unlocked':'In progress · finish the current story')+'</small></article></div><div class="meta-list"><div class="journal-line"><b>REPUTATION</b> Lyra '+state.rep.lyra+' · Orren '+state.rep.orren+' · Seer '+state.rep.seer+'</div><div class="journal-line"><b>EQUIPMENT</b> '+Object.values(state.equipment).filter(Boolean).length+' / 4 slots equipped · Ward '+state.stats.ward+' · Focus '+state.stats.focus+'</div><div class="journal-line"><b>WORLD</b> '+gates.filter(g=>state.quest>=g.unlock).length+' / '+gates.length+' routes available</div></div></div>'}
function loadState(){try{const raw=localStorage.getItem('ashen-crown-3d');if(raw){const saved=JSON.parse(raw);Object.assign(state,saved);state.equipment=Object.assign({core:null,charm:null,armor:null,relic:null},saved.equipment||{});state.stats=Object.assign({vitality:0,focus:0,ward:0},saved.stats||{});state.meta=Object.assign({renown:0,mastery:0,legacy:0,points:0,contracts:0},saved.meta||{});state.tutorial=false}}catch{}} 
function saveState(){try{localStorage.setItem('ashen-crown-3d',JSON.stringify(state))}catch{}}
function refreshEquipment(){document.querySelectorAll('.equip-slot').forEach(b=>{const x=state.equipment[b.dataset.slot];b.innerHTML=b.dataset.slot.toUpperCase()+'<span>'+(x?x.name:'Empty')+'</span>'});}
function openInventory(){refreshEquipment();const grid=$('inventoryGrid');grid.innerHTML=state.inventory.length?state.inventory.slice().reverse().map((i,idx)=>'<div class="inventory-item"><b>'+i.name+'</b><small>'+i.type+' · '+i.rarity+'</small><em>'+i.attrs.join(' · ')+'</em><button data-item="'+(state.inventory.length-1-idx)+'">EQUIP</button></div>').join(''):'<div class="inventory-item"><b>Your pack is empty</b><small>Explore the world and discover story items.</small></div>';$('inventoryMenu').classList.add('show');grid.querySelectorAll('button[data-item]').forEach(b=>b.onclick=()=>equipItem(Number(b.dataset.item)))}
function equipItem(index){const i=state.inventory[index];if(!i)return;const slot=i.type==='Armor'?'armor':i.type==='Trinket'?'charm':i.type==='Relic'?'relic':'core';state.equipment[slot]=i;if(i.attrs.includes('+Ward')||i.attrs.includes('Ward'))state.stats.ward=1;if(i.attrs.includes('+Vitality'))state.stats.vitality=1;if(i.attrs.includes('+Focus'))state.stats.focus=1;toastMsg(i.name+' equipped as '+slot);refreshEquipment();saveState()}
function renderWorldMap(){const el=$('mapWorld');el.innerHTML='';const points=[['Sanctuary',18,52,0,true],['Ember Grove',37,32,1,true],['Hollow Ruins',70,30,2,state.quest>=2],['Starfall Meadow',56,68,3,state.quest>=3],['Veil Lake',25,78,5,state.quest>=5],['Crown Road',82,70,6,state.quest>=6],['Starless Depths',74,88,9,state.quest>=9]];points.forEach(p=>{const d=document.createElement('div');d.className='map-node '+(p[4]?'open':'')+(p[0]===region()?' quest':'');d.style.left=p[1]+'%';d.style.top=p[2]+'%';d.innerHTML='<i></i><b>'+p[0]+'</b><small>'+(p[4]?'DISCOVERED':'LOCKED')+'</small>';el.appendChild(d)})}
function openMap(){renderWorldMap();$('worldMap').classList.add('show')}
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{keys[e.code]=true;if(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyE')interact();if(e.code==='KeyF')pulse();if(e.code==='KeyI')openInventory();if(e.code==='KeyM')openMap();if(e.code==='Slash'||e.code==='F1')$('tutorial').classList.add('show');if(e.code==='KeyJ'){$('journal').classList.toggle('show');renderJournal('story')}if(e.code==='KeyK')archive();if(e.code==='Escape'){$('pause').classList.toggle('show');state.paused=!state.paused}});window.addEventListener('keyup',e=>keys[e.code]=false);
canvas.addEventListener('mousedown',e=>{if(e.button===0)pulse();drag=true;lx=e.clientX;ly=e.clientY});window.addEventListener('mouseup',()=>drag=false);window.addEventListener('mousemove',e=>{if(!drag)return;yaw-=(e.clientX-lx)*.005;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-ly)*.003,-.1,.8);lx=e.clientX;ly=e.clientY});canvas.addEventListener('wheel',e=>{camera.fov=THREE.MathUtils.clamp(camera.fov+e.deltaY*.025,42,68);camera.updateProjectionMatrix()},{passive:true});
document.querySelectorAll('.journal-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.journal-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderJournal(b.dataset.tab)});
$('closeMeta').onclick=()=>$('metaMenu').classList.remove('show');$('closeInventory').onclick=()=>$('inventoryMenu').classList.remove('show');$('closeMap').onclick=()=>$('worldMap').classList.remove('show');$('tutorialStart').onclick=()=>{$('tutorial').classList.remove('show');state.tutorial=false;saveState()};$('helpButton').onclick=()=>$('tutorial').classList.add('show');$('closeDialogue').onclick=()=>$('dialogue').classList.remove('show');$('resume').onclick=()=>{$('pause').classList.remove('show');state.paused=false};
window.addEventListener('beforeunload',saveState);
loadState();setQuest();renderJournal('story');refreshEquipment();resize();if(state.tutorial!==false)$('tutorial').classList.add('show');toastMsg('3D RPG ready — WASD move, mouse camera, E interact, I inventory, M map');setInterval(()=>{if(!state.paused&&!document.hidden&&Math.random()<.55)spawnEnemy()},9000);
let last=performance.now();function frame(t){const dt=Math.min(.033,(t-last)/1000);last=t;if(!state.paused&&!$('dialogue').classList.contains('show')&&!$('tutorial').classList.contains('show')&&!$('inventoryMenu').classList.contains('show')&&!$('worldMap').classList.contains('show'))tick(dt);renderer.render(scene,camera);if(toastTimer>0&&(toastTimer-=dt)<=0)$('toast').classList.remove('show');requestAnimationFrame(frame)}requestAnimationFrame(frame);